### ISSUE TITLE
Forgets password even though batch is checked.

### ISSUE THREAD

**Issue by jeffshead** [openconnect/openconnect-gui#142]
### Description of the Issue

Does not auto fill password, all of the time. Does sometimes. Cannot reproduce at will. Sometimes I have to enter password and it remembers it for a few days.
### Specifications
- **Version**: 1.4.1 (also did this with older versions)
- **Platform**: Windows 7 x64, Enterprise US
### Prerequisites
- [x] Can you reproduce the problem?
- [x] Are you running the latest version?
### Steps to Reproduce the Issue

1. Enter info and connect. 
2. Batch is checked and profile saved.
3. Disconnect, connect again and have to enter password.
### Expected Behavior

Auto login
### Actual Behavior

Box pops up and have to enter password.
### Other Information

 This issue has been reported previously by others.

**Comment by horar** [comment]
I'm facing to this problem, but quite rarely

**Comment by ljacobs-sml** [comment]
This is the only draw back about your product right now. 

It really causes an unnecessary interruption in the workflow, especially since it's occurring not after _every_ iteration, but every few iterations, seemingly randomly. 

So you never know if you're going to get lucky or not.. and while I appreciate the small endorphin boost that accompanies a successful (no password prompt) connection attempt, it's not worth the frustration on the failed (password prompt) connection attempts.

I propose you elevate this bug to your immediate attention, and in return, I'd be glad to send some beer or coffee funds your way (if you have a donate button or paypal). It'd really be a big improvement to my life, and would be worth some financial compensation for otherwise free software.

**Comment by olegk82** [comment]
For me saving password - is the main advantage of openconnect over native Cisco AnyConnect app.
Please fix it as soon as possible.

**Comment by horar** [comment]
okey :-)

**Comment by ljacobs-sml** [comment]
I see progress is being made. Don't forget to add a [donate button](https://github.com/patharanordev/donate-in-git) when it's done!

**Comment by jan-glx** [comment]
With the [latest build](https://ci.appveyor.com/api/buildjobs/y3pp9s3brgaf5676/artifacts/build%2Fopenconnect-gui-1.5.2-win32.exe)  manually reconnecting (clicking `disconnect` and then `connect`) still asks for a password. Is this supposed to be the case?

**Comment by ljacobs-sml** [comment]
@jan-glx are you using batch mode? Also, I can only assume you're using 1.5.2 since you commented 7 days ago and 1.5.3 was just officially released yesterday 16 hours ago.

Try installing 1.5.3. I've only connected and disconnected a handful of times, but a coworker reported it seems to be working correctly now.

@horar I'm a man of my word, get that donate button up or send me your paypal email address... I've got $20 with your name on it!

**Comment by jan-glx** [comment]
@ljacobs-sml as the href of the link in my post shows, the tested build was before the version bump but should contain already the the fix in 77cbe92 . In the meantime I found an other issue preventing the use of the saved passed password and supplied a fix in [PR 229](https://github.com/openconnect/openconnect-gui/pull/229), which should be included in the just released 1.5.3.
