### ISSUE TITLE
Juniper cannot decode the realm form in Chinese

### ISSUE THREAD

**Issue by yaolu** [openconnect/openconnect-gui#162]
### Description of the Issue
When I try to connect to a juniper vpn, whose realm is described in Chinese. Openconnect failed to decode it. Thus make it impossible to choose it.

### Specifications
- **Version**: 7.06
- **Platform**: OSX, Linux64

### Prerequisites
* [x] Can you reproduce the problem?
* [ ] Are you running the latest version?

### Steps to Reproduce the Issue

1. openconnect --juniper vpn.tongji.cn
2. Then You can type in the "统一身份认证用户" shown in the form
3. Failed, Auth choice "统一身份认证用户" not available

### Expected Behavior
Choose the option correctly in the form

### Actual Behavior
There may be some decode problem, I cannot select it.

**Comment by horar** [comment]
Thanks!
Firstly, you should use newest version - the most actual release is openconnect v7.08 (with some juniper fixes).
Second, I tried reproduce this problem with openconnect v7.08 (macOS & winOS) and it's not working with newest version as well.

Looks like there is some problem with encoding or characters in group name. The output from oc-v7.08 was (macOS 10.12):
<pre>
# sudo openconnect --juniper vpn.tongji.cn
WARNING: Juniper Network Connect support is experimental.
It will probably be superseded by Junos Pulse support.
GET https://vpn.tongji.cn/
Connected to 222.66.109.15:443
SSL negotiation with vpn.tongji.cn
Connected to HTTPS on vpn.tongji.cn
Got HTTP response: HTTP/1.1 302 Found
GET https://vpn.tongji.cn/dana-na/auth/url_default/welcome.cgi
SSL negotiation with vpn.tongji.cn
Connected to HTTPS on vpn.tongji.cn
frmLogin
统一身份认证用户
校外用户        |
                ]:^Cfgets (stdin): Interrupted system call
</pre>
(I stop it with ctrl+c)

Because this project on GitHub is only GUI app on top of openconnect, could you please report it to [upstream project](http://www.infradead.org/openconnect/mail.html). You can just send an email, as explained or subscribe.
We have to look closely what is the problem.
Thanks.

**Comment by yaolu** [comment]
Hi Horar,

> SSL negotiation with vpn.tongji.cn
Connected to HTTPS on vpn.tongji.cn
frmLogin
统一身份认证用户
校外用户        |
                ]:^Cfgets (stdin): Interrupted system call

There're two options,  统一身份认证用户 and 校外用户,
if I paste the  统一身份认证用户 as my option input, it will return 

> Auth choice "统一身份认证用户" not available

This error can be reproduced in the v7.08 & v7.06 in Linux64

Thanks,
Yao

**Comment by horar** [comment]
Hi Yao,

yes, this is clear to me; but expected output is something like this:
<pre>
...
Connected to HTTPS on XXX
Please enter your username and password.
GROUP: [groupName1|groupName1|groupName1]:
...
</pre>

That is the reason to discuss this in upstream project with openconnect app/library author.
Thanks,
Lubomir.

**Comment by horar** [comment]
http://lists.infradead.org/pipermail/openconnect-devel/2017-March/004231.html
