### ISSUE TITLE
Error setting up DTLS

### ISSUE THREAD

**Issue by dvkwong** [openconnect/openconnect-gui#40]
I am using Windows 8.1 and also Win7 and am getting a Error setting DTLS. I have no idea why this would be failing. I can see from fragments of the log below that at the start there was a TLS connection error not sure if this is pertinent to the DTLS error further down the log.

Is anybody able to lead me in the right direction to resolve this issue please? Is there some debug logging I can turn on to get more diagnostic info?

Thanks

2015-06-05 21:34 Failed to read from SSL socket: The TLS connection was non-properly terminated.
2015-06-05 21:34 Error fetching HTTPS response
.....
2015-06-05 21:34 Configuring Legacy IP networks:
2015-06-05 21:34 Route configuration done.
2015-06-05 21:34 Error setting up DTLS

**Comment by dvkwong** [comment]
I just tested using the Android Open connect client and this works fine. I noticed in the logs that it does not seem to use DTLS, and seems to stop after setting the domains. Is there some way to disable this for the Windows client?

**Comment by iceberg1369** [comment]
try --no-dtls

**Comment by nmav** [comment]
In the settings page you can disable UDP (that's the same as DTLS).

**Comment by dvkwong** [comment]
I tried --no-dtls and disable UDP. I no longer get the DTLS error however I still cannot to any network resources. Comparing logs with the Android Openconnect there seems to be a few steps the Windows Open connect is not doing. Such as setting MTU, Route, DNS, Domain, however I may not be comparing like with like.

**Comment by nmav** [comment]
Let's separate any issues. openconnect-gui doesn't take command line parameters so --no-dtls wouldn't work. About setting mtu etc, it is unrelated to the issue at hand, so please open another bug if you think it is appropriate. As far as I understand the original bug is addressed.

**Comment by AshrazRashid** [comment]
Can i read password from file in command line?? using -b

**Comment by horar** [comment]
@AshrazRashid please don't drop your problem randomly to different ticket. This will not speed-up your problem solving. In addition, when you have problem with command line tool, the best place to ask is directly [infradead.org/openconnect/](http://infradead.org/openconnect/)

**Comment by AshrazRashid** [comment]
Sorry @horar this issue furstrated me and i am stuck since a month.. basically i want to connect openconnect using bash and read password from .txt file just.. command that i am using

type Pass.txt | openconnect.exe -v --passwd-on-stdin <Pass.txt --user=Username --os=win https://server.com

**also tried**

openconnect -v --printcookie --dump-http-traffic  --no-xmlpost --passwd-on-stdin <Pass.txt --os=win -u Username  server.com 

**but end of result is**

POST https://server.com/auth
 Attempting to connect to server ip:port
 Connected to ip:port
 SSL negotiation with server 
 Connected to HTTPS on server 
 Got HTTP response: HTTP/1.1 200 OK
 Set-Cookie: webvpncontext=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; Secure
 Content-Type: text/xml
 Content-Length: 306
 X-Transcend-Version: 1
 HTTP body length:  (306)
 XML POST enabled
 Please enter your username.
 POST https://server.com/auth
 Got HTTP response: HTTP/1.1 200 OK
 Set-Cookie: webvpncontext=eAgl06347RsfukD2978Fa5K5laO7sS/imPuRD6MZBNk=; Max-Age=120; Secure
 Content-Type: text/xml
 Content-Length: 310
 X-Transcend-Version: 1
 HTTP body length:  (310)
 Please enter your password.
 POST  https://server.com/auth
 Got HTTP response: HTTP/1.1 200 OK
 Set-Cookie: webvpncontext=eAgl06347RsfukD2978Fa5K5laO7sS/imPuRD6MZBNk=; Max-Age=120; Secure
 Content-Type: text/xml
 Content-Length: 324
 X-Transcend-Version: 1
 HTTP body length:  (324)
 Login failed.
Please enter your password.
 Password:

Please help me to find out where i made mistake.

Thanks
