### ISSUE TITLE
Juniper server support?

### ISSUE THREAD

**Issue by scw** [openconnect/openconnect-gui#69]
The included `openconnect.exe` doesn't seem to support Juniper clients. Could this be added?

**Comment by horar** [comment]
hi, on which version? Anyway, could you please test console client bundled with gui v1.4.0? Thanks

**Comment by horar** [comment]
Hi, any update?

**Comment by horar** [comment]
newer version will be bundled in next release

**Comment by irakhlin** [comment]
Hi I just wanted to help close the loop on this if its helpful. Currently I am able to build the actual openconnect command line client and library (32 and 64bit) with the new API that supports juniper. It all seems to work correctly. I am also able to build this project against those artifacts but forcing the default protocol to "nc" and proceeding to attempt a connection in the GUI will cause the same issue regardless of what I have tried. The connection establishes and authenticates fine but the entire client and gui completely crashes after about ~30 seconds. I havent had much time to look into it since then. Let me know if I can help at all in this.
