### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by nmav** [openconnect/openconnect-gui#70]
I have little to no available time to spent on that project. If you are interested in maintaining it please contact me. It is needed to demonstrate that ability by submitting pull requests which fix existing issues.

**Comment by horar** [comment]
Hi Nikos, I can help with UI & installer stuff. Is it possible that I will self-assigne issues to me, so we don't work together on the same problem? (will generate pull requests if something is done)
Thanks.

**Comment by nmav** [comment]
Thank you that would really help. I'll also create an issue with some comments I received by a UX designer in case you're interested at them.

**Comment by horar** [comment]
yeap, pls. one issue per one comment/idea if make sense
thanks

**Comment by nmav** [comment]
Already done in a single one. I'll split it to multiple.

**Comment by horar** [comment]
Hi @nmav to your question about release (from #80), I would like go through remaning tickets at first and fix/implement some of them and then I would like to clean compile warnings (Mac & Win) and slightly clean the UI code (aka refactor few variable names to have more descriptive strings instead of generic for e.g. buttons, labelts etc.). Do you prefer tickets for everything or I will just send pull requests of proposed changes?
Then we can let out next release...

**Comment by nmav** [comment]
I don't think we need tickets for everything. I'll add you to the group so you can add milestones.
